sudo: required

matrix:
  include:
    - name: "Python Tests"
      language: python
      python: 3.6
      install:
        - pip install codecov
        - pip install flake8
        - pip install mypy
        - pip install pylint
        - pip install pyparsing==2.4.0
      script:
        - make test_python
      after_success:
        - codecov

    - name: "SPARK Tests"
      env: TARGET="test_spark"

    - name: "SPARK Tests (without prefix)"
      env: TARGET="test_spark NOPREFIX=1"

    - name: "SPARK Verification"
      env: TARGET="prove_spark_ci"

    - name: "SPARK Verification (CVC4 only)"
      env: WRAPPER="travis_wait 111" TARGET="prove_spark_ci GNATPROVE_ARGS='--prover=cvc4 --steps=100000'"

    - name: "SPARK Verification (Z3 only)"
      env: WRAPPER="travis_wait 111" TARGET="prove_spark_ci GNATPROVE_ARGS='--prover=z3 --steps=100000'"

    - name: "SPARK Verification (Alt-Ergo only)"
      env: WRAPPER="travis_wait 111" TARGET="prove_spark_ci GNATPROVE_ARGS='--prover=altergo --steps=100000'"

script:
  - ${WRAPPER} docker run -v $PWD:/app -w /app jklmnn/gnat:gpl.2019.spark /bin/sh -c "make ${TARGET}"
